//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class BinaryNibble
    {
        public static void Binary()
        {
            Console.WriteLine("enter the decimal no");
            int x = Utility.UtiliReadInt();

            int y = Utility.SwapNibbles(x);
            Console.WriteLine(y);
            
            ////using only string here i have created an empty string and call the string again n again
            // String str1 = Utility.DeciToBinary(x);
            ////String of number is comming  
            
            //Console.WriteLine(str1);

            ////we cant split it causes its a one word string so we have to store the char into char array  
            //char[] str2 = new char[str1.Length];
            //str2 = str1.ToCharArray();

            ////nibble concept
            //int len = str2.Length-1;
            //int count = len;
            ////create an array
            //while (len >= 0)
            //{
            //    if (len >= 4)
            //    {
            //        char[] arr = new char[4];
                    
            //        for(int i = 3; i <= 0; i--)
            //        {
            //            arr[i] = str2[count];
            //            count--;
            //        }
            //        //now  calling the binary to decimal no.
            //        len = len - 4;
            //    }
            //    else
            //    {
            //        int[] arr = new int[len];
            //    }
            //}
            
            //double sum= Utility.BinaryToDeci(str2);         
           // Console.WriteLine(sum);
        }
       
    }
}
