//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class DecimalToBinary
    {
        public static void Binary()
        {
            Console.WriteLine("enter the decimal no");
            int x = Utility.UtiliReadInt();
            //using string builder..... but reverse no is comming here so i have 
                                //to reverse the array
            var str = new StringBuilder();
            // str.Append = "";
            

            //using only string here i have created an empty string and call the string again n again
            String str1 = "";
          
            while (x>0){
                int a = x % 2;
                //str.Append(a+" ");
                str1 = a+" "+str1;
                x = x / 2;
               
            }
            String s = str.ToString();
            Console.WriteLine(str1 + " ");
            

        }
    }
}
