//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class DecimalToBinary
    {
        public static void Binary()
        {
            Console.WriteLine("enter the decimal no");
            int x = Utility.UtiliReadInt();
            //using only string here i have created an empty string and call the string again n again        
            
           
            Console.WriteLine(Utility.DeciToBinary(x));


        }
       
    }
}
