//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class LeapYear
    {
        public static void Leap()
        {
            Console.Write("Enter the year");
            int year = int.Parse(Console.ReadLine());
            if(year>=1752 && year <= 9999)
            {
                if(year%4==0 || year%400==0 && year % 100 != 0)
                {
                    Console.Write("its a leap year ");
                }
                else
                {
                    Console.Write("Its not a leap year");
                }
            }
        }
    }
}
