
//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class PowerOf2
    {
        public static void Power()
        {
            Console.WriteLine("Enter the no up which you wanna print table of 2");
           
            int no = Utility.UtiliReadInt();

            double[] array = new double[no ];
            for (int i = 0; i < no; i++)
            {
                double a = Math.Pow(2, i);
                array[i] = a;
            }

            Utility.PrintArray(array,no);
            
        }
    }
}
