//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Diagnostics;

namespace FunctionalProgramming
{
    class Stopwatchs
    {
        public static void Stop()
        {
            Console.WriteLine("Enter 1 to start");
            int x = int.Parse(Console.ReadLine());                     
            int[] arr1 = Utility.Time(x);
            Console.WriteLine("Enter 1 to stop");
            int y= int.Parse(Console.ReadLine());
            int[] arr2 = Utility.Time(y);           
            //    //difference between the two time value.
            if (arr2[2] < arr1[2])
            {
                arr2[1] = arr2[1] - 1;
                arr2[2] += 60;
            }
            if (arr2[1] < arr1[1])
            {
                arr2[0] = arr2[0] - 1;
                arr2[1] += 60;
            }
            int sec = arr2[2] - arr1[2];            
            int min = arr2[1] - arr1[1];
            int hour = arr2[0] - arr1[0];
            if (hour < 0)
            {
                hour = 0;
            }
            Console.WriteLine("time: {0}:{1}:{2}", hour, min, sec);        
            }
        }    
    }


