//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class StringReplace
    {
       public static void Replace()
        {
            Console.WriteLine("Hello <<username>>, how are you");
            String str = Console.ReadLine();
            int l = str.Length;
            if (l >= 3)
            {
                Console.Write("Hello {0}, how are you", str);
            }
        }
    }
}
