//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class Utility
    {
        public static void  PrintLine(String x)
        {
            Console.WriteLine(x);
        }
        public static int UtiliReadInt()
        {
            int x = int.Parse(Console.ReadLine());
            return x;
        }
        public static double UtiliReadDouble()
        {
            int x = int.Parse(Console.ReadLine());
            return x;
        }
        public static String UtiliRead()
        {
            String x = Console.ReadLine();
            return x;
        }
        public static void PrintArray(double []value, int no)
        {
           
            for (int j = 0; j <= no; j++)
            {
                Console.WriteLine(value[j]);
            }
           
        }
        public static Boolean UtiliLeapYear(int year) 
        {
            if (year >= 1752 && year <= 9999)
            {
                if (year % 4 == 0 || year % 400 == 0 && year % 100 != 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            else
            {
                Console.WriteLine("invalide year");
            }
            return false;

        }
        public static double WindChill(int t, double v)
        {
            
                double w = 35.74 + 0.6215 * t + (0.4275 * t - 35.75) * Math.Pow(v,0.16);
               
            
            return w;
        }
        public static int[] Time(int x)
        {
            
                String x1 = DateTime.Now.ToLongTimeString().ToString();
                char[] spearator = { ':', ' ' };
                String[] st1 = x1.Split(spearator);
                int[] arr1 = new int[3];

                for (int i = 0; i < 3; i++)
                {
                    arr1[i] = int.Parse(st1[i]);
                }

                //Console.WriteLine("Enter 1 to stop");
                //int stop = int.Parse(Console.ReadLine());




            
            return arr1;
        }
    }
}
