//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class WindChill
    {
        public static void Wind()
        {
            Console.WriteLine("enter two parameter temperature and velocity of wind");
            Console.WriteLine("enter temperature ");
            int t = Utility.UtiliReadInt();
            Console.WriteLine("enter velocity of wind");
            double v= Utility.UtiliReadDouble();            
            if (v >= 3 && v <= 150)
            {
                double w=Utility.WindChill(t,v);
                if (w < 50)
                {
                    Console.WriteLine(w);
                }
                else
                {
                    Console.WriteLine("Invalid");
                }              
            }
            else
            {
                Console.WriteLine("Invalid");
            }
        }
    }
}
