//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace Algorithm
{
    class InsertionSort
    {
        public static void Insertion()
        {
            // int[] arr = { 50, 12, 10, 5, 7, 9, 13, 25 };
            Console.WriteLine("enter the words");
           String s= Console.ReadLine();
            String[] str = s.Split(" ");
            int l = str.Length;
            Utility.Insertion1(str, l);



        }
       
    }
}
