//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionalProgramming
{
    class HarmonicNumber
    {
        public static void Harmonic()
        {


            Console.WriteLine("enter the number up to which you can run the harmonic series");
            int no = int.Parse(Console.ReadLine());
            if (no <= 0)
            {
                Console.WriteLine("Invalide no for harmanic no");

            }
            else
            {

                float x = 0;
                for (float i = 1; i <= no; i++)
                {
                    x = x + (1 / i);

                }
                Console.Write(x);
            }
        }
    }
}
