//<auto-generated/>
using System;

namespace FunctionalProgramming
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Functional programming");
            Console.WriteLine("----------------------");
           
            Console.WriteLine(" Enter the no from 1 to 6");
            Console.WriteLine(" 1.User Input and Replace String Template “Hello <<UserName>>, How are you?” ");
            Console.WriteLine(" 2.Flip Coin and print percentage of Heads and Tails");
            Console.WriteLine(" 3.Leap Year");
            Console.WriteLine(" 4.Harmonic Number ");
            Console.WriteLine(" 5.Power of 2");
            Console.WriteLine(" 6.Factors");
            Console.WriteLine(" 7. 2D array");
            Console.WriteLine(" 8. Sum of three Integer adds to ZERO");
            Console.WriteLine(" 9.Euclidean distance from the point (x, y) to the origin (0, 0)");
            Console.WriteLine(" 10.Write a program Quadratic.java to find the roots of the equation a*x*x + b*x + c.");
            Console.WriteLine(" 11.Write a program Distance.java");
            Console.WriteLine(" 12.Write a program Quadratic.java ");
            Console.WriteLine(" 13.Write a program WindChill.java ");
            //Console.WriteLine(" Enter the no from 1 to 6");



            int str = int.Parse(Console.ReadLine());
            switch (str)
            {
                case 1:
                    //FunctionalProgramming.StringReplace();
                    StringReplace.Replace();
                    break;
                case 2:
                    HeadTail.Toss();
                    break;
                case 3:
                    LeapYear.Leap();
                    break;
                case 4:
                    HarmonicNumber.Harmonic();
                    break;
                case 5:
                    PowerOf2.Power();
                    break;
                case 6:
                    FactorNumber.Factor();
                    break;
                case 7:
                    TwoDArray.Two();
                    break;
                //case 8:
                //    SumOfThree.Sum();
                //    break;
                case 9:
                    Distance.Dist();
                    break;
                case 10:
                    Quadratic.Quad();
                    break;
                //case 11:
                //    WindChill.Wind();
                //    break;
                //case 12:
                //    Gambler.Game();
                //    break;
                //case 13:
                //    Coupon.Coup();
                //    break;
                //case 14:
                //    StopWatch.Stop();
                //    break;
                //case 15:
                //    TicTakTeo.Tic();
                //    break;

                default:
                    break;

            }


        }
    }
}
