//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace DataStructures
{
    class MyLinkedList
    {

       public Node1 head;
       public class Node1
        {
            public string data;
            public Node1 next;
            public Node1(string d)
            {
                data = d;
                next = null;
            }

        }
        //add in the last
        public void AddLast(string data)
        {
            Node1 newNode = new Node1(data);
            if (head == null)
            {
                head = newNode;
            }
            else
            {
                Node1 n = head;
                while (n.next != null)
                {
                    n = n.next;
                }
                n.next = newNode;
            }
        }
        //add in first
        public void AddFirst(string data)
        {
            Node1 NewNode = new Node1(data);
            NewNode.next = head;
            head = NewNode;
        }
        //display the linked list or print
        public void Display()
        {
            Console.WriteLine("Linklist elements are");
            Node1 temp = head;
            while (temp!= null)
            {
                Console.Write(temp.data+ " ");
                temp = temp.next;
            }
        }
        //delete the element from the linked list if the data is given
        public void DeleteLL(string data)
        {
           
                // Store head node 
                Node1 temp = head, prev = null;

                // If head node itself holds the key to be deleted 
                if (temp != null && temp.data == data)
                {
                    head = temp.next; // Changed head 
                    return;
                }

                // Search for the key to be deleted, keep track of the 
                // previous node as we need to change temp.next 
                while (temp != null && temp.data != data)
                {
                    prev = temp;
                    temp = temp.next;
                }

                // If key was not present in linked list 
                if (temp == null) return;

                // Unlink the node from linked list 
                prev.next = temp.next;
            
        }
        //checking whether the element are present on the link list or not
        public bool CheckLL(string data)
        {
            Node1 temp = head;
            if (temp != null && temp.data == data)
            {
                Console.WriteLine("element is found");
                return true;
            }
            while (temp != null && temp.data!=data)
            {
                temp = temp.next;
            }
            if (temp == null)
            {
                Console.WriteLine("element not found");
                return false;
            }
            else
            {
                Console.WriteLine("element found");
                return true;
            }
        }
        //adding the linklist to a given string
        public void WriteFile()
        {
            StringBuilder sb = new StringBuilder();
            Node1 temp = head;
            while (temp != null)
            {
                sb.Append(temp.data + " ");
                temp = temp.next;
            }
            string sb1 = sb.ToString();
            System.IO.File.WriteAllText(@"C:\Users\Neelabh\Desktop\GitHub\dataStructure\DataStructures\DataStructures\TextFile1.txt", sb1);

        }
    }
}

