//<auto-generated/>
using System;

namespace DataStructures
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Welcome to datastructure programming");
            Console.WriteLine("1.Unorder list");
            Console.WriteLine("2.Order list");
            Console.WriteLine("3.Balanched parentheses");
            int x = int.Parse(Console.ReadLine());
            switch (x)
            {
                case 1:
                    Unorderlist.Unorder();
                    break;
                case 2:
                    ListOrder.Order();
                    break;
                case 3:
                    BalanchedParentheses.Parentheses();
                    break;
               
                default:
                    break;
            }





        }
    }
}
