//<auto-generated/>
using System;

namespace DataStructures
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("enter digits 1");
            int x = int.Parse(Console.ReadLine());
            switch (x)
            {
                case 1:
                    Unorderlist.Unorder();
                    break;
                case 2:
                    ListOrder.Order();
                    break;
               
                default:
                    break;
            }





        }
    }
}
